version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./server
    ports:
      - "9000:9000"
    env_file:
      - .env
    depends_on:
      - db
      - broker
    # networks:
    #   - internal_network

  frontend:
    container_name: frontend
    ports:
      - "443:443"
      - "8000:8000"
    build:
      context: ./frontend
    restart: always
    env_file:
      - .env
    depends_on:
      - backend

  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env

  broker:
    container_name: broker
    image: redis

volumes:
  data:

# networks:
#   internal_network:
#     internal: true
