version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: ./server
      args:
        - DEV=true #개발 단계에서만 사용하는 requirements.dev.txt를 사용할 수 있음
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    container_name: frontend
    image: nginx
    ports:
      - "443:443"
      - "9000:9000"
    build:
      context: ./frontend
    restart: always
    depends_on:
      - backend

  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env


volumes:
  data:
