version: "3.9"

services:
  server:
    build:
      context: .
      args:
        - DEV=true #개발 단계에서만 사용하는 requirements.dev.txt를 사용할 수 있음
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=pongdb
      - DB_USER=ponguser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - pong-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pongdb
      - POSTGRES_USER=ponguser
      - POSTGRES_PASSWORD=changeme


volumes:
  pong-db-data:
